# Generated by Django 4.0.3 on 2022-03-15 12:04

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
